import * as THREE from "three";

export interface RegionBounds {
  minX: number;
  maxX: number;
  minZ: number;
  maxZ: number;
  minY: number;
  maxY: number;
}

export interface RegionMeshData {
  region: number;
  name: string;
  source: { dof: string; minimap: string };
  vertexCount: number;
  indexCount: number;
  vertices: number[];
  indices: number[];
  bounds: RegionBounds;
  spawn: { x: number; y: number; z: number };
  heights?: { size: number; step: number; data: number[] };
  blocks: { id: number; name: string; floor: number }[];
}

export interface BuildingSlice {
  v0: number;
  vCount: number;
  i0: number;
  iCount: number;
  page: number;
}

export interface BuildingInstance {
  g: number;
  x: number;
  y: number;
  z: number;
  ry: number;
}

export interface NpcPlacement {
  x: number;
  z: number;
}

export interface NpcGroupManifest {
  geom: number;
  name: string;
  kind: "mob" | "npc";
  instances: NpcPlacement[];
}

export interface BuildingsManifest {
  atlas: string[];
  pageSize: number;
  geoms: BuildingSlice[];
  instances: BuildingInstance[];
  npcGroups: NpcGroupManifest[];
}

export interface WorldBuildings {
  manifest: BuildingsManifest;
  geometry: THREE.BufferGeometry;
  atlasTextures: THREE.Texture[];
}

export interface RegionAssets {
  data: RegionMeshData;
  texture: THREE.Texture;
  floorGeometry: THREE.BufferGeometry;
  spawn: THREE.Vector3;
  buildings?: WorldBuildings;
}

function sampleTerrainHeight(data: RegionMeshData, x: number, z: number): number {
  const h = data.heights;
  if (!h || !h.data.length) return data.spawn.y;
  const G = h.size;
  const step = h.step;
  const fx = Math.max(0, Math.min(G - 1, x / step));
  const fz = Math.max(0, Math.min(G - 1, z / step));
  const x0 = Math.floor(fx);
  const z0 = Math.floor(fz);
  const x1 = Math.min(x0 + 1, G - 1);
  const z1 = Math.min(z0 + 1, G - 1);
  const t = h.data;
  const h00 = t[z0 * G + x0];
  const h10 = t[z0 * G + x1];
  const h01 = t[z1 * G + x0];
  const h11 = t[z1 * G + x1];
  const ax = fx - x0;
  const az = fz - z0;
  return h00 * (1 - ax) * (1 - az) + h10 * ax * (1 - az) + h01 * (1 - ax) * az + h11 * ax * az;
}

export { sampleTerrainHeight };

// RegionLoader loads a verified 3D region (geometry + texture generated from the
// external package). Region 1 (Constantinople) carries an extra buildings
// manifest (buildings.json + buildings.bgeo + atlas webp pages) generated by
// scripts/generate_region_ct.py.
export class RegionLoader {
  static async load(regionId: number): Promise<RegionAssets> {
    const base = `/assets/img/silkroad/game/region${regionId}`;
    const meshRes = await fetch(`${base}/mesh.json`);
    if (!meshRes.ok) {
      throw new Error(`Region ${regionId} mesh not found (${meshRes.status})`);
    }
    const data = (await meshRes.json()) as RegionMeshData;
    if (data.region !== regionId) {
      throw new Error(`Region asset mismatch: expected ${regionId}, got ${data.region}`);
    }

    const texture = await this.loadTexture(`${base}/floor.webp`);

    const positions = new Float32Array((data.vertices.length / 5) * 3);
    const uvs = new Float32Array((data.vertices.length / 5) * 2);
    for (let i = 0; i < data.vertexCount; i++) {
      const o = i * 5;
      positions[i * 3] = data.vertices[o];
      positions[i * 3 + 1] = data.vertices[o + 1];
      positions[i * 3 + 2] = data.vertices[o + 2];
      uvs[i * 2] = data.vertices[o + 3];
      uvs[i * 2 + 1] = 1 - data.vertices[o + 4];
    }

    const indices = new Uint32Array(data.indices);
    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute("position", new THREE.BufferAttribute(positions, 3));
    geometry.setAttribute("uv", new THREE.BufferAttribute(uvs, 2));
    geometry.setIndex(new THREE.BufferAttribute(indices, 1));
    geometry.computeVertexNormals();

    const assets: RegionAssets = {
      data,
      texture,
      floorGeometry: geometry,
      spawn: new THREE.Vector3(data.spawn.x, data.spawn.y, data.spawn.z),
    };

    const bRes = await fetch(`${base}/buildings.json`);
    if (bRes.ok) {
      assets.buildings = await this.loadBuildings(base, (await bRes.json()) as BuildingsManifest);
    }
    return assets;
  }

  private static async loadBuildings(base: string, manifest: BuildingsManifest): Promise<WorldBuildings> {
    const geoRes = await fetch(`${base}/buildings.bgeo`);
    if (!geoRes.ok) {
      throw new Error(`buildings.bgeo not found (${geoRes.status})`);
    }
    const buf = await geoRes.arrayBuffer();
    const dv = new DataView(buf);
    const sig = new TextDecoder().decode(new Uint8Array(buf, 0, 8));
    if (sig !== "SROBGEO1") {
      throw new Error(`bad bgeo signature: ${sig}`);
    }
    const vertTotal = dv.getUint32(8, true);
    const idxTotal = dv.getUint32(12, true);
    const positions = new Float32Array(vertTotal * 3);
    const uvs = new Float32Array(vertTotal * 2);
    const indices = new Uint32Array(idxTotal);
    let p = 16;
    const f32 = new Float32Array(buf, p, vertTotal * 5);
    for (let i = 0; i < vertTotal; i++) {
      positions[i * 3] = f32[i * 5];
      positions[i * 3 + 1] = f32[i * 5 + 1];
      positions[i * 3 + 2] = f32[i * 5 + 2];
      uvs[i * 2] = f32[i * 5 + 3];
      uvs[i * 2 + 1] = f32[i * 5 + 4];
    }
    p += vertTotal * 5 * 4;
    const u32 = new Uint32Array(buf, p, idxTotal);
    indices.set(u32);

    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute("position", new THREE.BufferAttribute(positions, 3));
    geometry.setAttribute("uv", new THREE.BufferAttribute(uvs, 2));
    geometry.setIndex(new THREE.BufferAttribute(indices, 1));
    geometry.computeVertexNormals();

    const atlasTextures = await Promise.all(manifest.atlas.map((a) => this.loadTexture(`${base}/${a}`)));
    return { manifest, geometry, atlasTextures };
  }

  private static loadTexture(url: string): Promise<THREE.Texture> {
    return new Promise((resolve, reject) => {
      const loader = new THREE.TextureLoader();
      loader.load(
        url,
        (tex) => {
          tex.colorSpace = THREE.SRGBColorSpace;
          tex.anisotropy = 4;
          resolve(tex);
        },
        undefined,
        (err) => reject(err),
      );
    });
  }
}
