#!/usr/bin/env python3
"""Region code resolver over the committed client + server region tables.

Combines two committed derived tables into one proven lookup from a packed
region code to everything known about that world region:

  * android/app/src/main/assets/game/textdata/regioncode.tsv  (client table,
    generated by build_textdata_catalog.py from Media.pk2 textdata; col1 =
    region id, col2 = RN_* string code, col3 = localized name).
  * android/app/src/main/assets/game/world/region_zone.tsv    (server table,
    generated by build_region_ref_catalog.py from SR_GameRefData/RefRegion.txt;
    col0 = region id, col1/2 = sector x/y, col3 = server name, col4 = flag,
    col5 = zone id).

Proven coordinate facts used here (see WORLD_COORDINATE_SYSTEM.md):
  * region id -> sector: sector_x = id & 0xFF, sector_y = id >> 8 (verified on
    2444 RefRegion rows: id == (y << 8) | x with 0 mismatches).
  * instance/dungeon codes carry the high bit (id < 0 in signed 16-bit); their
    coordinate space is UNKNOWN and is never derived here (sector -> None).

Data quirks handled deterministically:
  * regioncode.tsv has 7 region ids with duplicate rows (22478 has two
    distinct RN_* names; 25289-25294 repeat the same row). First row wins.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPTS))

from world_terrain import unpack_region  # noqa: E402


@dataclass(frozen=True)
class RegionEntry:
    """Everything proven about one packed region code."""

    region_id: int
    name_code: str | None
    localized_name: str | None
    server_name: str | None
    zone_id: str | None
    flag: str | None

    @property
    def is_instance(self) -> bool:
        return self.region_id < 0

    @property
    def sector_x(self) -> int | None:
        if self.is_instance:
            return None
        return unpack_region(self.region_id)[0]

    @property
    def sector_y(self) -> int | None:
        if self.is_instance:
            return None
        return unpack_region(self.region_id)[1]


class RegionResolver:
    """Proven region lookups over the committed client + server tables."""

    def __init__(self, regioncode: dict[int, tuple[str, str]], region_zone: dict[int, tuple[str, str, str, str, str]]):
        self._client = regioncode
        self._server = region_zone

    @classmethod
    def load_default(cls, assets: Path | None = None) -> "RegionResolver":
        base = (assets or (SCRIPTS.parent / "android/app/src/main/assets/game"))
        return cls.load(
            base / "textdata" / "regioncode.tsv",
            base / "world" / "region_zone.tsv",
        )

    @classmethod
    def load(cls, regioncode_path: Path, region_zone_path: Path) -> "RegionResolver":
        client = {}
        for line in regioncode_path.read_text(encoding="utf-8").splitlines():
            cells = line.split("\t")
            if len(cells) < 4 or not cells[1].strip().lstrip("-").isdigit():
                continue
            rid = int(cells[1])
            if rid not in client:
                client[rid] = (cells[2], cells[3])
        server = {}
        for line in region_zone_path.read_text(encoding="utf-8").splitlines():
            if line.startswith("#"):
                continue
            cells = line.split("\t")
            if len(cells) < 6:
                continue
            server[int(cells[0])] = (cells[1], cells[2], cells[3], cells[4], cells[5])
        return cls(client, server)

    def resolve(self, region_id: int) -> RegionEntry | None:
        """Return a proven RegionEntry, or None when the code is unknown."""
        if region_id not in self._client and region_id not in self._server:
            return None
        name_code, localized = self._client.get(region_id, (None, None))
        sx, sy, server_name, flag, zone = self._server.get(
            region_id, (None, None, None, None, None)
        )
        return RegionEntry(
            region_id=region_id,
            name_code=name_code,
            localized_name=localized,
            server_name=server_name,
            zone_id=zone,
            flag=flag,
        )

    def by_name_code(self, code: str) -> list[RegionEntry]:
        out = []
        for rid, (rc, _n) in self._client.items():
            if rc == code:
                entry = self.resolve(rid)
                if entry is not None:
                    out.append(entry)
        return out

    def region_ids(self) -> frozenset[int]:
        return frozenset(self._client) | frozenset(self._server)

    def sector_coverage(self) -> frozenset[tuple[int, int]]:
        return frozenset(unpack_region(rid) for rid in self._server)
